build: update Renku version
SwissDataScienceCenter/renku-project-template pull request #93
Opened 2020-10-06 14:45 UTC by pameladelgado

2020-10-12 14:01 UTC, rokroskar requested changes

2020-10-12 14:01 UTC, rokroskar commented on julia-minimal/Dockerfile
> +ARG RENKU_VERSION=0.11.4
The julia docker build doesn't use this yet

2020-10-12 14:03 UTC, pameladelgado commented on julia-minimal/Dockerfile
> +ARG RENKU_VERSION=0.11.4
right, I'll take it off for now then

2020-10-14 07:32 UTC, rokroskar commented
In the meantime 0.11.5 has been released :)

2020-10-16 07:33 UTC, rokroskar submitted a review, later dismissed

2020-10-21 10:18 UTC, ableuler approved these changes

2020-10-21 10:19 UTC, merged